services:
  - type: cron
    name: yad2-agent-bot
    env: python
    schedule: "0 * * * *"  # Запуск каждый час
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.
    
        envVars:
  - key: TELEGRAM_TOKEN
    value: "8729304576:AAGbNUeaWw9byg1w1Nu1AGCMraOXL6VN-Mk"
  - key: CHAT_ID
    value: "5242236154"